cloud:
  aws:
    credentials:
      access-key: ASIAW3MECWYJVRIERD7P
      secret-key: KG4vm4bbMVDEzGJDIS7HyVzosdzsCYmuPkDu+Sc6

    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: s3-woofjoy
    url: https://s3-woofjoy.s3.amazonaws.com/

paypal:
  client:
    id: Aa9pgs56xlqwjBXIz_JzLJU7FkOsBj87uER3Ib_1cyx05wPRGBOH59TxJvLkAPFsSutU8JEgJo7fu751
    secret: EJnwaoRs5uTVbQ2B_CtJ7vl6dWy6oKzRrDRsPm1Zp-9HUvpfIbqAuLYjZPb8ldSF0K2l0w5Caq5EZj6k
  mode: sandbox

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080