cloud:
  aws:
    credentials:
      access-key: ASIAW3MECWYJVRIERD7P
      secret-key: KG4vm4bbMVDEzGJDIS7HyVzosdzsCYmuPkDu+Sc6

    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: woofjoy-img
    url: https://woofjoy-img.s3.amazonaws.com/

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080